# -*- coding: utf-8 -*-
"""confidence intervals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjNDESHA3vGNtfae4mTNhsYN80DygJJB
"""

import numpy as np
from scipy import stats

data =[172,168,180,165,170,173,169,176]
n=len(data)
mean=np.mean(data)
se=stats.sem(data)

ci=stats.t.interval( confidence=0.95, df=n+1, loc=mean, scale=se )

print(f"Sample size:{n}")
print(f"Sample mean:{mean:.2f}")
print(f"Std error:{se:.2f}")
print(f"95% CI : {ci[0]:.2f},{ci[1]:.2f}")

# Changing the Intervals Level

ci_99= stats.t.interval(0.99,df=n+1,loc=mean,scale=se)
print(f"99% CI:({ci_99[0]:.2f},{ci_99[1]:.2f})")