# -*- coding: utf-8 -*-
"""scipy_ttest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aDrR1VC18n-vryjSo9EMICGg9R2FRik
"""

from scipy import stats
import numpy as np

A = [2.1,2.5,2.3,1.9,2.8,2.2,2.6,2]
B = [3.1,2.9,3.4,3,2.7,3.2,3.5,2.8]

t_stat,p_value = stats.ttest_ind(A,B,alternative = 'less')

print(f"t統計量: {t_stat:.4f}")
print(f"p値: {p_value:.4f}")
alpha = 0.01
if p_value < alpha:
  print(f"→ p={p_value:.4f} < α={alpha}: 帰無仮説を棄却（有意差あり）")
else:
  print(f"→ p={p_value:.4f} ≥ α={alpha}: 帰無仮説を採択（有意差なし）")